title: SqrRooT_2의 PS 블로그
description: SqrRooT_2 (wken2824) 가 PS 관련 글 올리는 블로그입니다.
show_downloads: true

baseurl: 
url: "https://SqrRooT-2.github.io" # change this to the base hostname & protocol for your site


google_analytics:

cayman-blog:
  date_format: "%Y-%m-%d %H:%M"

theme: # leave it empty

# social
author: SqrRooT_2
image: /thumbnail.png

plugins:
  - jekyll-target-blank

target-blank:
    rel: nofollow

header_page_refs: ['about', 'categories', 'tags', 'posts']
