# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "SqrRooT_2의 PS블로그"
description: "SqrRooT_2 (wken2824)가 운영하는 PS블로그입니다."

email: "2147483648ll@gmail.com"
#blog logo
logo: "/assets/images/df_logo.jpg"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/df_logo.jpg"

name: 'SqrRooT_2'
author: 'SqrRooT_2'
author_image: "/assets/images/df_logo.jpg"

paginate:	5

url: "http://SqrRooT-2.github.io" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:

  - icon:	github
    url:	https://github.com/SqrRooT-2
    desc:	github profile
    share_url:
    share_title:
    share_link:
